version: '3.5'
services:
  nhsd.buyingcatalogue.ordering.api:
    image: ${REGISTRY:-nhsd}/buying-catalogue/ordering-api:${TAG:-latest}
    container_name: ordering_api
    build: 
      context: .
      dockerfile: src/NHSD.BuyingCatalogue.Ordering.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: 
      - /bin/sh
      - -c 
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && dotnet /app/NHSD.BuyingCatalogue.Ordering.Api.dll
    networks:
      - nhsd_bcnetwork
    ports:
      - "8076:80"

networks: 
  nhsd_bcnetwork:
    name: nhsd_bcnetwork
    driver: bridge
