version: '3.5'

services:

  nhsd.buyingcatalogue.ordering.api:
    image: ${REGISTRY:-nhsd}/buying-catalogue/ordering-isapi:${TAG:-latest}
    container_name: ordering_api
    build: 
      context: .
      dockerfile: src/NHSD.BuyingCatalogue.Ordering.Api/Dockerfile
